import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart';
import 'services/auth_service.dart';
import 'services/property_service.dart';
import 'services/car_service.dart';
import 'services/location_service.dart';
import 'services/booking_service.dart';
import 'services/notification_service.dart';
import 'models/user_model.dart';
import 'utils/theme.dart';
import 'utils/constants.dart';
import 'views/home/home_screen.dart';

// Import Firebase options generated by flutterfire
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('Firebase initialization error: $e');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(create: (_) => AuthService()),
        Provider<PropertyService>(create: (_) => PropertyService()),
        Provider<CarService>(create: (_) => CarService()),
        Provider<LocationService>(create: (_) => LocationService()),
        Provider<BookingService>(create: (_) => BookingService()),
        Provider<NotificationService>(create: (_) => NotificationService()),
        StreamProvider<User?>(
          create: (context) => context.read<AuthService>().user,
          initialData: FirebaseAuth.instance.currentUser,
          lazy: false,
        ),
        StreamProvider<UserModel?>(
          create: (context) => context.read<AuthService>().userModel,
          initialData: null,
          lazy: false,
        ),
      ],
      child: MaterialApp(
        title: AppConstants.appName,
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        home: const HomeScreen(),
      ),
    );
  }
}
